-- 코드를 입력하세요
SELECT I.FOOD_TYPE, I.REST_ID,I.REST_NAME, I.FAVORITES
FROM REST_INFO I
WHERE I.FAVORITES = (SELECT MAX(B.FAVORITES)
                    FROM REST_INFO B
                    WHERE I.FOOD_TYPE = B.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC

